language: java
sudo: true
jdk: oraclejdk8

env:
  global:
  - TERM=dumb #Avoid chaos in Travis log

install: /bin/true #Travis runs "./gradlew assemble" by default

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew artifactoryPublish
    skip_cleanup: true
    on:
      tags: true
